# Server
server:
  port: 8080

# Profiles
spring:
  profiles:
    active: prod
  data:
    redis:
      host: localhost
      port: 6379

# Swagger (Springdoc OpenAPI)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# JWT
jwt:
  access-token-validity: 60000
  refresh-token-validity: 604800000